### ISSUE TITLE
Unable to connect to non-modded server

### ISSUE THREAD

**Issue by kolderz** [adde0109/Ambassador#11]
Some players cannot join the server for some reason. I think if you fix this error, the mod will become really stable.
This error shows up in the proxy. 

Here's the log:  https://pastebin.com/raw/TnmB7w5X
> exception encountered in org.adde0109.ambassador.velocity.backend.ForgeHandshakeSessionHandler@54ec7a05
> java.lang.IllegalStateException: The continuation can only be resumed once.
> 	at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.resume(VelocityEventManager.java:565) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.resume(VelocityEventManager.java:558) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at org.adde0109.ambassador.forge.FML2ClientConnectionPhase.complete(FML2ClientConnectionPhase.java:94) ~[?:?]
> 	at org.adde0109.ambassador.velocity.backend.ForgeHandshakeSessionHandler.handle(ForgeHandshakeSessionHandler.java:52) ~[?:?]
> 	at com.velocitypowered.proxy.protocol.packet.ServerLoginSuccess.handle(ServerLoginSuccess.java:125) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:143) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by adde0109** [comment]
Did you by any chance encounter another error relating to my plugin before this one?

**Comment by kolderz** [comment]
I don't think so, the server starts with no errors or warnings.

**Comment by adde0109** [comment]
How can I reproduce this?

**Comment by adde0109** [comment]
Could you try with the latest version and see if the issue is still there?
