### ISSUE TITLE
Incomplete set of tags received from server with some mods

### ISSUE THREAD

**Issue by Kamiszewskyy** [adde0109/Ambassador#12]
Hi, when I connect to my lobby with my forge 1.16.5 modpack (Oceanblock), I get disconnected and this message 
![image](https://user-images.githubusercontent.com/62818516/214606732-07e272bd-b696-4777-9cf8-52895759426c.png)

Lobby: Paper 1.12.2 with ViaVersion 
Proxy: Velocity with Ambassador
Main: Mohist 1.16.5 with Ambassador forge mod

I've found that this happens with only some mods and some not. For example when I tried to connect with only Applied Energetics 2, it worked fine. Unfortunately when I try to connect using Oceanblock I get this message as on the Image above.

**Comment by adde0109** [comment]
Happens when connecting to vanilla because some mods require tags that vanilla doesn't have. Mod related issue/bug.
