### ISSUE TITLE
[1.19.2] Failed to parse version spec [1.19.2)

### ISSUE THREAD

**Issue by AnCasper** [adde0109/Ambassador#14]
ATM 8 - Server will not start with (ambassador-forge-1.19.2-0.2.1.jar)

Modpack - All The Mods 8 - Version 1.0.10
Forge - 43.2.3

Debug - https://mcpaste.io/0994d469d6ef3f60
Error - https://mcpaste.io/7a391ac1876badd2

**Comment by AnCasper** [comment]
https://github.com/adde0109/Proxy-Compatible-Forge/compare/1.16.5...AnCasper:Proxy-Compatible-Forge:patch-1

**Comment by unilock** [comment]
The bug was fixed for 1.19.2 in https://github.com/adde0109/Proxy-Compatible-Forge/commit/88f7cdd315974ebd0c5d1377dd6f8444ca1f8c32, but it looks like a new release containing that fix hasn't been published yet.
