### ISSUE TITLE
[Bug] An internal error occurred in your connection

### ISSUE THREAD

**Issue by isaaclepes** [adde0109/Ambassador#16]
Velocity 3.2.0
ambassador 1.1.7-alpha

After Velocity has been running for about 24 to 48 hrs, users attempting to connect to Forge instance receive "An internal error has occurred in your connection". The only solution is to restart Velocity, whereby users will be able to join again. 

Also, when it is operating 'correctly', Forge users will receive a timeout error on their first connection attempt, but succeed on the second attempt to join.

Vanilla and Forge clients joining a vanilla instance do not have any connection issues, even when the Forge users are having problems joining the Forge instance.

**Comment by adde0109** [comment]
Try using the latest version

**Comment by adde0109** [comment]
Also you may need to increase the timeout in the velocity config if you use heavy mods because they need time to initialize for the first connection.

**Comment by isaaclepes** [comment]
I've been testing the new version for about a week and the problem has not returned. Closing issue.
