### ISSUE TITLE
Negotiating...

### ISSUE THREAD

**Issue by Teastrands** [adde0109/Ambassador#17]
90% of users can connect between servers just fine. Here is an example of a negotiating... bug after the latest update.

Proxy is running latest ambassador/velocity
Lobby is 1.19 spigot, modded servers are 1.16.5 pixelmon on arclight with PCF mod

https://pastebin.com/TyZAAkH7

**Comment by adde0109** [comment]
Can't see anything in this log. Please upload debug.log if you can.

**Comment by Teastrands** [comment]
Here is the debug log, and here is the instance from server console:
https://pastebin.com/qjazkUpR
[debug.log](https://github.com/adde0109/Ambassador/files/10877138/debug.log)

**Comment by Teastrands** [comment]
Here is another player who is experiencing the issue. I am not seeing anything helpful in the debug server log or velocity log.

https://pastebin.com/XLfYVu7R

**Comment by adde0109** [comment]
Seems like a bug related to protocollib not PCF or ambassador.

**Comment by Teastrands** [comment]
Fixed by changing to the following settings and allowing more time for the connection to happen

ambassador config-
reset-timeout = 10000
server-switch-cancellation-time = 15

velocity config-
connection-timeout = 11000

Thank you for your help and the awesome mod.
