### ISSUE TITLE
mismatched mods

### ISSUE THREAD

**Issue by Spreax** [adde0109/Ambassador#19]
So I have no idea if I'm doing anything wrong. Keep in mind i set velocity to modern forwarding so my modded server is joinable

<img width="290" alt="image" src="https://user-images.githubusercontent.com/106390400/224122928-b89e7949-573d-41e4-8ea8-96d2ef544b05.png">

Im running on a 1.17.1 spigot server. I want to use this vanilla spigot server lobby that goes to my 1.16.5 spigot forge hybrid server (arclight)

thanks

**Comment by adde0109** [comment]
Post debug.log from the forge server

**Comment by Spreax** [comment]
nevermind I fixed it. Was a bug with broken plugins that were out of date.
