### ISSUE TITLE
CorruptedFrameException - Direwolf20 1.19.2

### ISSUE THREAD

**Issue by Aiidoneus** [adde0109/Ambassador#21]
Hello,

I am running:
velocity-3.2.0-SNAPSHOT-243.jar
Ambassador-Velocity-1.2.0-beta-all.jar

with the modpack:
Direwolf20 1.19.2  version 1.7.0 https://www.feed-the-beast.com/modpacks/101-ftb-presents-direwolf20-119 

I am using Modern player info forwarding mode on velocity with `_proxy-compatible-forge-1.19.2-1.0.2.jar` on the forge server. I have tried other forwarding modes with no luck either. Here is the error I get on velocity's side: https://gist.github.com/Aiidoneus/462a75ce844d767dfd0dec03bb21a903

I do notice that it thinks the client is trying to connect with a 1.19.1 Minecraft protocol when it should be 1.19.2 if that means anything. I am able to direct connect to the server without velocity just fine (for testing) and have a vanilla paper server working just fine. 

Feel free to ask me questions or get a hold of me on discord at Aidoneus#4656

**Comment by adde0109** [comment]
This just got fixed. Compile from source and from both the ambassador repo and the pcf repo if you can.

**Comment by Sir-Will** [comment]
Which Java version should be used to build it? I'm getting this error:

![](https://i.imgur.com/rSFYJ6c.png)

**Comment by adde0109** [comment]
Java 17

**Comment by Sir-Will** [comment]
Ah, weird. Tried that one too and was unable to build it, because of the error below.

![](https://i.imgur.com/iRaUlL2.png)

**Comment by adde0109** [comment]
Did you also clone the Velocity repository inside the Velocity folder?

**Comment by Sir-Will** [comment]
Yes, `git clone --recurse-submodules git@github.com:adde0109/Ambassador.git`

**Comment by Sir-Will** [comment]
I'm also able to build Velocity.

**Comment by adde0109** [comment]
Make sure JDK is correctly configured with gradle. It looks like it can't find it properly.
