### ISSUE TITLE
Reconnect required for non-modded servers

### ISSUE THREAD

**Issue by iLemon** [adde0109/Ambassador#22]
My network has a problem where if you connect to the forge server, and then switch back to any other paper server, you'll still be required to reconnect.

For example if your network setup is like this:

velocity:
  - hub (runs paper)
  - forge
  - skyblock (runs paper)

Reprod steps:
1. Connect to network and be in the hub.
2. Connect to the forge server, you'll be required to reconnect as intended
3. Switch back to the hub, or vanilla server, you'll be required to reconnect, not intended
4. Reconnect and you'll be forced to reconnect for every single server switch, even if they're all to non-forge servers.

I'm running Ambassador 1.3.1 from discord.

**Comment by adde0109** [comment]
This is intended in order for Forge to reset and deactivate mods when switching into vanilla. It is possible to avoid the reset but it may come with some instability depending on the mods.

**Comment by adde0109** [comment]
An option in the config file could be added to override this behaviour.

**Comment by iLemon** [comment]
The problem is more that it happens when going from vanilla <-> vanilla, as long as you've joined forge at least once.

**Comment by adde0109** [comment]
I will look into that
