### ISSUE TITLE
Stuck on negotiating even when timout is high.

### ISSUE THREAD

**Issue by adde0109** [adde0109/Ambassador#28]
Happens when switching servers

**Comment by kolderz** [comment]
Lots of our players are stuck on the negotiation screen, and combined with a bad internet connection, the chance you can join a 1.16 server is almost equal to zero.

I don't see any logs or errors; it's really hard to detect the problem. I even tried to read client logs, but it gave me nothing useful

**Comment by adde0109** [comment]
In the debug.log file on the client there should be some information on if the client receives any handshake messages after the reset. Does the client receive anything after the reset has started?

**Comment by kolderz** [comment]
I will try to get them to send me the file then I will send it to you in Discord, it would be for me difficult since most of them are bad at doing simple computer stuff, and some are not even willing to send me the debug file because they're scared of privacy.

**Comment by adde0109** [comment]
I think this is related to the client reset packet mod. I'm currently looking into an alternative method/mod.

**Comment by CitrusHappy** [comment]
Notice this behavior in my setup as well. 

Its currently only occurring when two players attempt a connection with /server at the same exact time. The player who gets second to connect is always stuck negotiating while the other player gets through the connect.

**Comment by adde0109** [comment]
One discovery I recently made is that this could be caused by the Client Reset Packet mod not working well with other mods. Removing some mods might make it work better.

**Comment by adde0109** [comment]
Closing because this isn't an Ambassador issue anymore with the release of 1.4.0-beta
