### ISSUE TITLE
Unable to connect to modded server (All the Mods 7 1.18) with legacy or modern ip forwarding

### ISSUE THREAD

**Issue by ZiroGX2** [adde0109/Ambassador#3]
![Screenshot_6](https://user-images.githubusercontent.com/22279426/182001843-0c99a77b-3f86-4bc9-9f16-46e9c3316fe7.png)
![Screenshot_7](https://user-images.githubusercontent.com/22279426/182001844-049643dd-0d3a-4eda-8254-bfbf44b83264.png)
![Screenshot_5](https://user-images.githubusercontent.com/22279426/182001845-7ce953fc-150e-47c9-a3bd-7ab7c0d3c2cc.png)
![Screenshot_8](https://user-images.githubusercontent.com/22279426/182001868-d62682c4-daa5-4dd2-95dc-3977bfefe4aa.png)
I have attempted to join with legacy and modern ip forwarding and also tried the forced setting with both. I also have tried compiling the 1.18.2 branch manually but to no avail. Let me know if you want more information.

**Comment by adde0109** [comment]
1.18 is currently in development. The current 1.18 release (v0.1) is deprecated and will bot work right now with latest ambassador. V0.2 is currently in the works.

**Comment by ZiroGX2** [comment]
Ok thanks. In the meantime which version of ambassador should I use on the velocity end.

**Comment by adde0109** [comment]
Nvm, fixed it. 
Here is the velocity plugin: https://github.com/adde0109/Ambassador/releases/tag/0.3.2
And here is the forge mod: https://github.com/adde0109/Ambassador-Forge/releases/tag/v0.2.0

**Comment by ZiroGX2** [comment]
Update does not seem to change anything at least for all the mods 7.
To begin with modern forwarding:
![Screenshot_12](https://user-images.githubusercontent.com/22279426/182326767-10ec2f08-8d3f-4ea7-8e73-7fa3e5310517.png)
![Screenshot_11](https://user-images.githubusercontent.com/22279426/182326769-e9464b15-592f-49cd-8855-fe5bf70bdfd6.png)
And Legacy forwarding:
![Screenshot_13](https://user-images.githubusercontent.com/22279426/182326849-1fe918c5-5de5-4d2f-b568-918fdf588ed8.png)

Let me know if there is anything else I can provide.

**Comment by adde0109** [comment]
Are you using Arclight or mohist?

**Comment by adde0109** [comment]
I found the problem, seems like the modern forwarding packet handler mistook a handshake packet for the modern forwarding response packet. I tested it on atm7 and it should work now.
Fixed : https://github.com/adde0109/Ambassador-Forge/releases/tag/v0.2.0](https://github.com/adde0109/Ambassador-Forge/releases/tag/v0.2.1
