### ISSUE TITLE
Unable to connect to lobby

### ISSUE THREAD

**Issue by thebebee** [adde0109/Ambassador#30]
Every time I use Ambassador I am unable to connect to my proxy, and I get "Unable to connect to lobby: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!" I remove the plugin and it works again so I think I have the bungeecord config correct.

**Comment by adde0109** [comment]
What version?

**Comment by thebebee** [comment]
> What version?

tested on 1.3.2 and 1.3.1 with velocity 3.2.0

**Comment by adde0109** [comment]
Could you share your setup? What software do you use?

**Comment by thebebee** [comment]
windows 10, java 17, velocity for proxy, paper for hub server. server works without ambassador but cant connect to forge server that's on magma. with ambassador I cant join the hub server at all

**Comment by adde0109** [comment]
Use Arclight instead, magma is not supported.

**Comment by adde0109** [comment]
Magma is not supported

**Comment by thebebee** [comment]
> Magma is not supported

is paper still okay, for the hub? i replaced magma for arclight and I'm getting the same issue. without ambassador, I get "This server has mods that require forge... etc"

**Comment by adde0109** [comment]
Paper works. But i'm certain something is wrong with the info player forwarding. Do you have any other plugin on the proxy?

**Comment by thebebee** [comment]
> Paper works. But i'm certain something is wrong with the info player forwarding. Do you have any other plugin on the proxy?

just luckperms for velocity

**Comment by thebebee** [comment]
i got ambassador working after a fresh install, fixed something along the way ig, now I'm stuck on "Your server did not send a forwarding request to the proxy", after negotiating.

**Comment by wolflord212312** [comment]
So that issue with magma
We are adding modern forwarding support directly into magma
from our testing with ambassador at least in 1.19.3 you can connect no issues

I have not tested modern forwarding in 1.18.2 yet
![2023-05-25_21 58 31](https://github.com/adde0109/Ambassador/assets/47831173/d2863a0f-1e6d-478d-92ef-ff976ec81716)

But look forward to it

main issue now is commands we will need to add some way to fix command auto complete

**Comment by wolflord212312** [comment]
Witch it seems that adde0109 you have made a fix for this can you send me the classes you use for this as we will most likely add communication with ambassador if that is how you are doing it.

**Comment by wolflord212312** [comment]
Magma now has a version that works with ambassador (: for 1.18.2 and 1.19.3
