### ISSUE TITLE
Incompatibility with BungeeGuard+

### ISSUE THREAD

**Issue by M4RC0Sx** [adde0109/Ambassador#31]
I does not allow to join forge servers (in this case, hybrid with BungeeGuard+ correctly installed in backend and proxy servers) if you have BungeeGuard+ installed and bungeeguard forward mode on velocity config toml.

Using latest version of Ambassador and BungeeGuard+: https://github.com/nickuc/BungeeGuardPlus

**Comment by M4RC0Sx** [comment]
If you enable Bungeeguard forwarding mode on Velocity, you cannot join the server either.

**Comment by adde0109** [comment]
Should be resolved with version 1.4.2
