### ISSUE TITLE
Stuck on 'negotiating' if backend server kick the player while login in

### ISSUE THREAD

**Issue by manugame** [adde0109/Ambassador#33]
If a player is switching from lobby (papermc) to backend (forge 1.19.2) and get kicked while login in, he get stuck on 'negotiating'.

To reproduce, simply disconnect the player from Forge event "PlayerNegotiationEvent".

**Comment by C0D3-M4513R** [comment]
iirc this is a common issue with Forge Client Reset Packet.

**Comment by wolflord212312** [comment]
This is a fixed issue in latest 1.19.2 Forge Client Reset packet
people dont keep up with updates do they?

https://www.curseforge.com/minecraft/mc-mods/forge-client-reset-packet-forward/files/4653659

**Comment by wolflord212312** [comment]
This can be closed.

**Comment by manugame** [comment]
yes this is fixed with the latest reset packet mod update.
