### ISSUE TITLE
Stuck on invalid player data

### ISSUE THREAD

**Issue by chrgargar4** [adde0109/Ambassador#37]
Im running arclight 1.19.2 and velocity modern forward with ambassador and PCF and Im getting "invalid player data" every time I try to join the server, tried reseting it and creating a new one but still the same.

Any possible fix? Thanks.

![image](https://github.com/adde0109/Ambassador/assets/65631716/5082e9f2-b7fb-4b3c-8f12-68cfca61e4ce)

**Comment by adde0109** [comment]
Have you tired connecting directly without proxy?

**Comment by chrgargar4** [comment]
Without proxy it says "direct connections are not permited", I get this 2 errors since I installed ambassador and pcf, without them I could join without proxies with no errors.

Here you have the "invalid player data" console error.

![image](https://github.com/adde0109/Ambassador/assets/65631716/cd4bb71b-d558-4ef5-855f-55f32a77d952)

And the "direct connections are not permited" idk if it may help.

![image](https://github.com/adde0109/Ambassador/assets/65631716/b940fe70-3186-4f75-8d59-4c63eeb63b0a)

**Comment by adde0109** [comment]
Try without any secret in the pcf config.

**Comment by chrgargar4** [comment]
![image](https://github.com/adde0109/Ambassador/assets/65631716/99677971-2391-4654-b7c3-b286a8bf1bc0)

![image](https://github.com/adde0109/Ambassador/assets/65631716/2231ad33-14a0-45c6-8448-a55a9f49d7e4)

**Comment by adde0109** [comment]
No I meant connect to it directly without the secret in the pcf config.

**Comment by chrgargar4** [comment]
Oh sorry.

I've tried now connecting directly without secret but same "invalid player data" and "couldnt place player in world" in console.

**Comment by adde0109** [comment]
Ok, repeat what you just did but remove the PCF mod.

**Comment by chrgargar4** [comment]
Yes i can join directly without the mod.

**Comment by adde0109** [comment]
Is the client Forge or vanilla?

**Comment by chrgargar4** [comment]
Vanilla, I just tried forge and got this: 

![image](https://github.com/adde0109/Ambassador/assets/65631716/9384525f-ba6b-4418-b286-5112f4bc15a7)

**Comment by adde0109** [comment]
Does this also happen without PCF?

**Comment by adde0109** [comment]
I will try to reproduce it myself and see if I can fix it.

**Comment by chrgargar4** [comment]
No dw I finally fixed it, after installing forge I couldnt join the server but then I tried to remove ambassador then added it again and it worked lol.

Thank you for all your help and your soon replies.

I have 2 questions, is it possible to have vanilla hub which u can join without installing any mod and then be able to redirect ppl to a modded server?

And when I redirect to a second server I get this item:
![image](https://github.com/adde0109/Ambassador/assets/65631716/e0259be7-4e74-41d1-ab65-74445869b2f7)
I didnt have this item before installing PCF/Ambassador/modern forwarding, is this from velocity/PCF/Ambassador? Is there any way I can disable/modify this item? 🤔

Again thank you so much for your help 😄.

**Comment by adde0109** [comment]
1. Yes there should be a way, keep in mind that server switching without having to reconnect is not possible without the client having a mod.
2. Neither Ambassador or PCF interact with the game world so it's impossible that one of my plugins gave you that item. Must be from one of the other plugins you have.
