### ISSUE TITLE
Connectivity problems

### ISSUE THREAD

**Issue by chrgargar4** [adde0109/Ambassador#38]
Im facing these two problems:

![image](https://github.com/adde0109/Ambassador/assets/65631716/cb192195-9683-4e23-bc07-d820496e3332)
From what I know the first error only appears on some users.

The second one is: out-of-order chat packet received. Did you system time change?

This second error is much more common.

Im not sure if its a velocity problem or an ambassador issue since I had the exact same server without proxy and didnt get these errors.

I hope you can help me :/.

Thanks.

**Comment by adde0109** [comment]
Could you provide what plugins you use?

**Comment by chrgargar4** [comment]
Ambassador, JPremium, luckperms, and nuvotifier

**Comment by adde0109** [comment]
Please provide all versions of the software you are using like, MC version, Forge version, Velocity version, Ambassador version and mods/modpack you are using.

**Comment by adde0109** [comment]
Closed due to not enough information.
