### ISSUE TITLE
Can't work in latest version of velocity

### ISSUE THREAD

**Issue by thggdx** [adde0109/Ambassador#44]
Ambassador cannot work after velocity build ID 319

### Version Information
> Velocity: 3.3.0-SNAPSHOT
> Velocity build ID: 320
> Ambassador: 1.4.3-beta
> Minecraft: 1.20.1
> Forge: 47.2.19

### Plugin list
> Ambassador

[latest.log](https://github.com/adde0109/Ambassador/files/13930820/latest.log)

**Comment by MODNMETL** [comment]
Yeah we've just realised the same issue, too. Might need to downgrade Velocity while waiting for a fix

It looks like it's probably this: 319 Add ModernForgeConnectionType to supports Forge-1.20.2+

**Comment by RegressiaUK** [comment]
I can confirm this bug and same error in the log file.
1.20.1 
Forge 47.2.0
velocity-3.3.0-SNAPSHOT-327

**Comment by adde0109** [comment]
Latest commit fixes this issue, be prepared for a new release soon.
