### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by Icosider** [adde0109/Ambassador#46]
I have updated Velocity, the ForgeClientResetPacket client mod is 0.2.3. When i try to connect on second server, i get this error:
![image](https://github.com/adde0109/Ambassador/assets/9529993/d0b61015-2e21-4e20-8bc3-815edf2c45e2)

In console:
```txt
 unable to connect to server factions
com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.
```

Minecraft version: 1.19.2
Velocity version: velocity-3.3.0-SNAPSHOT-330
Forge version: 43.3.7
Forge mods: proxy-compatible-forge-1.19.2-1.1.4

**Comment by adde0109** [comment]
Could you confirm that the client has loaded the ForgeClientResetPacket client mod? You could go into "mods" in the main menu.

**Comment by adde0109** [comment]
Oh, my bad. You have the wrong version of the ForgeClientResetPacket client mod. For 1.19.2 it should be 0.2.2 not 0.2.3.

**Comment by Icosider** [comment]
![image](https://github.com/adde0109/Ambassador/assets/9529993/76437836-c345-495c-970f-4564a199820d)
In folder:
![image](https://github.com/adde0109/Ambassador/assets/9529993/94ffd59c-bac4-4203-8edf-e4d682297212)
On Forge servers:
![image](https://github.com/adde0109/Ambassador/assets/9529993/fe79c4df-cabb-49de-9d02-38d9edccb9e9)

On Velocity
![image](https://github.com/adde0109/Ambassador/assets/9529993/c092b9b6-13f7-438c-8e3d-dc01cb87cd4f)
![image](https://github.com/adde0109/Ambassador/assets/9529993/8e948966-4844-4624-b493-1bdefad433af)

And when i switch the server:
![image](https://github.com/adde0109/Ambassador/assets/9529993/fb7d3fc2-3cca-41b2-86d4-5fd7087ac0da)

**Comment by Icosider** [comment]
In console:
![image](https://github.com/adde0109/Ambassador/assets/9529993/9093b44c-e05d-4778-b94b-50b37ad84ec7)

**Comment by Icosider** [comment]
What other information should I provide?

**Comment by Icosider** [comment]
Figured out what the problem was! The problem was that my world contained missing blocks from the Botania mod. There is no fashion itself and the Ambassador takes this into account and does not allow on the connection to server. Disabling it in the config might have saved me.

If the configuration itself in the config actually only allows you to log in to the server with missing blocks/items/entities, then I think this can only cause problems with transferring inventory from one server to another. In other cases, in theory, there should be no problems.

Could you add an explanation to the configuration file that if the block/item/entity is missing in the world, then it will not be allowed either and the setting must be turned on to true?

**Comment by adde0109** [comment]
I thought you wanted to use reset packet mod because you had the wrong version installed. The chat says 'Reset type: NONE' which means that the client reset packet mod isn't used. The registries are saved in the level.dat file. Botana might have caused the registries to be different on the other server.
