### ISSUE TITLE
Incompatibility issues with Mohist Server's Velocity Support

### ISSUE THREAD

**Issue by 8MiYile** [adde0109/Ambassador#56]
> [!TIP]
> Server Info (Version)
Velocity: 3.3.0
Ambassador: 1.4.4
Backend Server: Mohist
Mohist: 1.18.2-173

## How To Work in not include Proxy-Compatible-Forge
Mohist have a config file in path `mohist-config/mohist.yml`
this config include velocity options

## My Suggesstion
Compatible Mohist Server's Velocity Support

## Screenshot
![image](https://github.com/adde0109/Ambassador/assets/25455400/d6b2a157-1a47-44c1-852a-1822ec5569e6)

## Extra Link
[Mohist](https://mohistmc.com)

**Comment by p0t4t0sandwich** [comment]
If Mohist doesn't implement command argument wrapping like PCF does, then command arguments probably won't work right.
This would be an issue to fix on Mohist's end, so the issue isn't needed here.
