### ISSUE TITLE
Cannot Connect to Vanilla Paper Server With Vanilla Client

### ISSUE THREAD

**Issue by elizabethlfransen** [adde0109/Ambassador#58]
Velocity Version: velocity-3.3.0-SNAPSHOT-396
Ambassador Version: Ambassador-Velocity-1.4.4-all
Server Version: 1.20.6
Client Logs: https://mclo.gs/bAkoVw5
Proxy Logs: https://mclo.gs/HvNPDFU

---

My current servers setup has a vanilla hub server, vanilla server, and a modded server when trying to connect I receive the error:
```
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket Direction CLIENTBOUND Protocol 1.20.5 State PLAY ID 11
```

This doesn't happen consistently I believe it affects **all** players after **any** player joins our modded server.

**Comment by elizabethlfransen** [comment]
This issue doesn't seem to occur with 1.5.0-rc1-beta with registry check disabled

**Comment by adde0109** [comment]
This is not ambassador's fault. The server has commands that velocity cannot decode and therefore needs wrapping, like what Proxy-Compatible-Forge does. Unfortunately a 1.20.6 version of PCF doesn't yet because I haven't have time to port it yet.

**Comment by adde0109** [comment]
I would also like to add that Ambassador only touches 1.20.1 and older.
