### ISSUE TITLE
Nothing happens when placed in velocity plugins folder.

### ISSUE THREAD

**Issue by Tromas06** [adde0109/Ambassador#6]
I downloaded the ambassador folder and placed it into the velocity plugins folder, relaunched velocity but upon startup velocity says "loaded 0 plugins" and I did not notice any change of files.  Is this normal?  I did not see the ambassador.toml to edit.

**Comment by adde0109** [comment]
Ambassador folder? Are you sure you downloaded the right thing? It should be a .jar file. Here is where you should download from: https://github.com/adde0109/Ambassador/releases

**Comment by Tromas06** [comment]
That makes sense. I was unable to find that download.  Ill try that.  Thank you.
