### ISSUE TITLE
1.21 vanilla client/server support

### ISSUE THREAD

**Issue by CursedHawk** [adde0109/Ambassador#61]
Hi, 

i found bug when trying to connect to Paper 1.21 server with Ambassador installed.

`[18:05:40 ERROR]: [server connection] CursedHawk420 -> surv: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@41f0b4d8
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket Direction CLIENTBOUND Protocol 1.21 State PLAY ID 11`

Uninstalling Ambassador makes it able again for vanilla clients to connect paper servers, but modded 1.20.1 clients tring connect to forge servers wont work anymore. 

Could you please add support for 1.21? 
Thank you, btw very nice plugin, works great for a long time 👍

**Comment by adde0109** [comment]
Velocity supports forge 1.20.2 and onwards without Ambassador. What you are looking for is a server side mod to fix the available command arguments issue. My mod PCF solves this but hasn't been ported to that version yet.

**Comment by CursedHawk** [comment]
The problem is that vanilla clients cant connect to paper servers with ambassador installed on Velocity.

**Comment by CREW8** [comment]
I have a similar Problem. If i install Ambassador i neither can join my Paper Servers nor my Forge Servers.
If i remove Ambassador i can join my Paper Servers again, but if i try to join the Forge Server i get the Error with something like "Denied Vanilla Client" even if i am using a forge modded Client.

**Comment by Illusionika** [comment]
I'm having this problem too. Here's the Velocity log.  https://mclo.gs/wlRNOMz


Someone seems to have discovered why. https://github.com/PaperMC/Velocity/issues/1365#issuecomment-2196096966

**Comment by TerroFlys** [comment]
> I'm having this problem too. Here's the Velocity log. https://mclo.gs/wlRNOMz
> 
> Someone seems to have discovered why. [PaperMC/Velocity#1365 (comment)](https://github.com/PaperMC/Velocity/issues/1365#issuecomment-2196096966)

I have a similar problem as well. Any way to fix this?

**Comment by Illusionika** [comment]
> > 我也遇到了这个问题。这是 Velocity 日志。 [https://mclo.gs/wlRNOMz  ](https://mclo.gs/wlRNOMz)
> > 似乎有人发现了原因。   [PaperMC/Velocity#1365 （评论）  ](https://github.com/PaperMC/Velocity/issues/1365#issuecomment-2196096966)
> 
> 我也有类似的问题。 有什么办法解决这个问题吗？

deop

**Comment by Mac898** [comment]
I'm not entirely sure what I am doing, but I did manage to solve the issue in Ambassador.

See patch below:
https://github.com/adde0109/Ambassador/compare/v1.4.4...Mac898:Ambassador:patch-bypass-argument-id-issue

**Comment by Willsr71** [comment]
> I'm not entirely sure what I am doing, but I did manage to solve the issue in Ambassador.
> 
> See patch below: [v1.4.4...Mac898:Ambassador:patch-bypass-argument-id-issue](https://github.com/adde0109/Ambassador/compare/v1.4.4...Mac898:Ambassador:patch-bypass-argument-id-issue)

This fixed it for me as well, thank you

**Comment by Mac898** [comment]
I havent tested it with Forge backend on 1.20.2+ If I get around to testing it and verify it at least superficially works, I will create a PR for it.

**Comment by TerroFlys** [comment]
Havent been able to solve this yet but the issue seems to be that the lobby is a vanilla (paper) server.

**Comment by adde0109** [comment]
A fix has been released with v1.4.5.
