### ISSUE TITLE
Problem with switching between forge servers

### ISSUE THREAD

**Issue by WhiteNoise1010** [adde0109/Ambassador#63]
Every time I switch servers, I can't connect to the server.
The error message is as follows.
`[Server thread/INFO] [minecraft/ServerLoginPacketListenerImpl]: com.mojang.authlib.GameProfile@3244f9c4[id=ff8f192b-e0fa-3376-8643-ba66ff8e79d9,name=WhiteNoise1010,properties={},legacy=false] (/[::1]:2309) lost connection: Disconnected`

There is no problem when connecting to the server.
When switching servers, the message "Please Reconnect" is displayed, and when I reconnect, I can connect.
It seems to be an online-mode issue, but the online-mode is turned off on the backend.

There is nothing installed on both backend servers except 'proxy-compatible-forge',
and there is nothing installed on velocity except 'Ambassador'.
The client also connected without any mods installed.

I hope this helps, velocity.toml, backend server logs, and server.properties are attached.

And versions used are as follows:
Forge version: 1.20.1-47.3.3
Velocity version: 3.3.0-SNAPSHOT-400
Ambassador version: 1.4.4
proxy compatible forge version: 1.20-1.1.4

[ambassador_logs.zip](https://github.com/user-attachments/files/16071111/ambassador_logs.zip)

**Comment by TheFlash787** [comment]
@WhiteNoise1010 Server switching on Forge is not possible without a client reset packet mod installed.

However, if you update to the 1.5 betas, this is no longer required.

**Comment by adde0109** [comment]
This is intended behavior.
