### ISSUE TITLE
Cant use * perm node 1.16.5 ARCLIGHT

### ISSUE THREAD

**Issue by Liopoxys** [adde0109/Ambassador#7]
Hello im using ambassador inside my velocity proxy, but im getting this
Velocity log:
https://pastebin.com/7Tw2UECD

Player log: https://pastebin.com/DwRKbxRD

i can join server if i dont have * perm on my user but if i put it it disconnects me and cant join back

**Comment by adde0109** [comment]
Hi, are you using Ambassador-Forge/Proxy-Compatible-Forge mod on your Arclight server?

**Comment by xism4** [comment]
> Hi, are you using Ambassador-Forge/Proxy-Compatible-Forge mod on your Arclight server?

That issue is known already with LuckPerms, it crashes when it gives * permission for some reason
