### ISSUE TITLE
cannot mix modded and unmodded servers on proxy

### ISSUE THREAD

**Issue by OfficiallySp** [adde0109/Ambassador#9]
not sure if this is intentional but i run a network with a vanilla server and a modded server but cannot connect to the vanilla one while using this plugin on my backend. is this intentional behaviour?

**Comment by adde0109** [comment]
No there is something wrong here, you should be able...

What error do you get when trying to connect to the Vanilla server?

**Comment by OfficiallySp** [comment]
hi. sorry I thought i replied. my mistake. didn't see this. The issue turned out to be a specific plugin. everything works now.

**Comment by Spreax** [comment]
What plugin was it? I'm also getting a similar issue.
